import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Leaf, ShieldCheck, Sprout, Users } from "lucide-react";
import { PageHero } from "@/components/PageHero";

export const metadata: Metadata = { title: "Proiecte GIUVA - Acțiuni concrete pentru comunitate", description: "Vezi proiectele active GIUVA și implică-te în transformarea comunității tale." };

const projects = [
  { title: "Comunitatea în Acțiune", status: "activ", icon: Leaf, impact: "spații publice mai curate și comunități locale implicate", duration: "martie - octombrie 2026", partners: "parteneri locali de formalizat", text: "Curățenie urbană, plantări de copaci și reabilitarea spațiilor publice prin voluntariat civic." },
  { title: "Prim Ajutor pentru Toți", status: "activ", icon: ShieldCheck, impact: "mai multă educație de prim ajutor și awareness DAE", duration: "în curs", partners: "parteneri autorizați viitori", text: "Cursuri și sesiuni de informare pentru elevi, adulți și comunități locale." },
  { title: "Grădina Comunitară Oradea", status: "în pregătire", icon: Sprout, impact: "educație ecologică și solidaritate locală", duration: "toamna 2026", partners: "comunități locale", text: "Înființarea unei grădini comunitare ca spațiu de educație, întâlnire și producție solidară." },
  { title: "Europa în Mișcare", status: "planificat", icon: Users, impact: "schimburi civice între comunități GIUVA", duration: "roadmap 2027", partners: "programe europene viitoare", text: "Schimburi de voluntari între București, Oradea și orașe europene, după formalizarea cadrului." }
];

export default function ProjectsPage() { return <><PageHero eyebrow="Proiecte" title="Proiecte GIUVA - Transformăm idei în acțiuni" text="Transformăm idei în acțiuni concrete pentru comunitate. Proiectele sunt prezentate prudent, cu statut clar și fără parteneriate implicite." actions={[{ href: "/implica-te", label: "Implică-te" }, { href: "/contact", label: "Propune o idee", tone: "ghost" }]} /><section className="px-5 pb-20"><div className="mx-auto max-w-7xl"><div className="mb-8 flex flex-wrap gap-2">{["active", "în pregătire", "planificate", "finalizate"].map((f) => <span key={f} className="rounded-full border border-slate-200 px-4 py-2 text-sm font-black text-[#081f3a]">{f}</span>)}</div><div className="grid gap-5 md:grid-cols-2">{projects.map((project) => { const Icon = project.icon; return <article key={project.title} className="card p-7"><div className="flex items-start justify-between gap-4"><Icon className="text-[#16825d]" size={34}/><span className="rounded-full bg-[#f8f9fa] px-3 py-2 text-xs font-black uppercase text-[#081f3a]">{project.status}</span></div><h2 className="mt-5 text-3xl font-black text-[#081f3a]">{project.title}</h2><p className="mt-4 leading-7 text-slate-600">{project.text}</p><div className="mt-5 grid gap-2 text-sm font-semibold text-slate-600"><p><strong>Impact estimat:</strong> {project.impact}</p><p><strong>Durată:</strong> {project.duration}</p><p><strong>Parteneri:</strong> {project.partners}</p></div><Link href="/contact" className="mt-5 inline-flex items-center gap-2 font-black text-[#1f5fbf]">Află mai multe<ArrowRight size={16}/></Link></article>; })}</div></div></section></>; }